#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/install_pgo.sh [options]

Install the pgo launcher for the current clone and create a local user config.

Options:
  --bin-dir DIR       Directory for the pgo launcher (default: $HOME/bin, or PGO_BIN_DIR)
  --config PATH       Config path (default: $HOME/.config/pgo/projects.conf, or PGO_CONFIG)
  --copy              Copy the launcher instead of symlinking it
  --force-config      Replace an existing config file
  --update-shell      Add the launcher directory to $HOME/.zshrc if needed (default)
  --no-update-shell   Do not modify shell startup files
  -h, --help          Show this help

This does not install Pi on the host and does not store API keys in the repo.
EOF
}

die() {
  echo "install_pgo: $*" >&2
  exit 1
}

expand_home() {
  local value="$1"
  case "$value" in
    "~")
      printf '%s' "$HOME"
      ;;
    "~/"*)
      printf '%s/%s' "$HOME" "${value#"~/"}"
      ;;
    "\$HOME")
      printf '%s' "$HOME"
      ;;
    "\$HOME/"*)
      printf '%s/%s' "$HOME" "${value#"\$HOME/"}"
      ;;
    *)
      printf '%s' "$value"
      ;;
  esac
}

portable_path() {
  local expanded="$1"
  case "$expanded" in
    "$HOME")
      printf '$HOME'
      ;;
    "$HOME/"*)
      printf '$HOME/%s' "${expanded#"$HOME/"}"
      ;;
    *)
      printf '%s' "$expanded"
      ;;
  esac
}

bin_dir="${PGO_BIN_DIR:-$HOME/bin}"
config_path="${PGO_CONFIG:-$HOME/.config/pgo/projects.conf}"
install_mode="symlink"
force_config=0
update_shell=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bin-dir)
      bin_dir="${2:?missing bin directory}"
      shift 2
      ;;
    --config)
      config_path="${2:?missing config path}"
      shift 2
      ;;
    --copy)
      install_mode="copy"
      shift
      ;;
    --force-config)
      force_config=1
      shift
      ;;
    --update-shell)
      update_shell=1
      shift
      ;;
    --no-update-shell)
      update_shell=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

bin_dir="$(expand_home "$bin_dir")"
config_path="$(expand_home "$config_path")"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
launcher_source="$repo_root/templates/pgo"
runner_path="$repo_root/scripts/run_pi_docker.sh"
build_path="$repo_root/scripts/build_pi_docker.sh"
key_script="$repo_root/scripts/add_pgo_key.sh"
provider_script="$repo_root/scripts/add_pgo_provider.sh"
project_script="$repo_root/scripts/add_pgo_project.sh"
runner_config="$(portable_path "$runner_path")"

[[ -f "$launcher_source" ]] || die "launcher template not found: $launcher_source"
[[ -f "$runner_path" ]] || die "Docker runner not found: $runner_path"
[[ -f "$build_path" ]] || die "Docker build script not found: $build_path"
[[ -f "$key_script" ]] || die "Keychain helper not found: $key_script"
[[ -f "$provider_script" ]] || die "provider helper not found: $provider_script"
[[ -f "$project_script" ]] || die "project helper not found: $project_script"

mkdir -p "$bin_dir"
chmod +x "$launcher_source" "$runner_path" "$build_path" "$key_script" "$provider_script" "$project_script"

if [[ "$install_mode" == "copy" ]]; then
  cp "$launcher_source" "$bin_dir/pgo"
  chmod +x "$bin_dir/pgo"
else
  ln -sf "$launcher_source" "$bin_dir/pgo"
fi

config_dir="$(dirname "$config_path")"
mkdir -p "$config_dir"

if [[ -f "$config_path" && "$force_config" -eq 0 ]]; then
  config_status="left existing config unchanged"
else
  cat > "$config_path" <<EOF
# pgo local project config
# Generated by scripts/install_pgo.sh
#
# This file stores paths and model choices only. Do not put API keys here.

runner = $runner_config

# Add a provider before running pgo:
#   scripts/add_pgo_provider.sh
#
# Example provider fields:
# base_url = https://your-provider.example/v1
# model = your-model-id
#
# The Keychain item should contain a key for the configured base_url.
keychain_service = pgo_ak
keychain_account = pgo_ak
api_key_env = pgo_ak

# Named projects are added with:
#   scripts/add_pgo_project.sh

# Optional per-project overrides.
# model.work-app = company-model-id
# base_url.work-app = https://your-provider.example/v1
# keychain_service.work-app = pgo_work_ak
# keychain_account.work-app = pgo_work_ak
EOF
  config_status="wrote config"
fi

path_status=""
case ":$PATH:" in
  *":$bin_dir:"*)
    path_status="launcher directory is already on PATH"
    ;;
  *)
    if [[ "$update_shell" -eq 1 ]]; then
      zshrc="$HOME/.zshrc"
      mkdir -p "$(dirname "$zshrc")"
      path_line="export PATH=\"$bin_dir:\$PATH\""
      if [[ -f "$zshrc" ]] && grep -F "$path_line" "$zshrc" >/dev/null 2>&1; then
        path_status="PATH line already present in $zshrc; open a new shell or run: source $zshrc"
      else
        tmp_zshrc="$(mktemp "${zshrc}.XXXXXX")"
        if [[ -f "$zshrc" ]] && grep -F '#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!' "$zshrc" >/dev/null 2>&1; then
          awk -v path_line="$path_line" '
            BEGIN { inserted = 0 }
            !inserted && $0 == "#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!" {
              print ""
              print "# pgo launcher"
              print path_line
              print ""
              inserted = 1
            }
            { print }
            END {
              if (!inserted) {
                print ""
                print "# pgo launcher"
                print path_line
              }
            }
          ' "$zshrc" > "$tmp_zshrc"
        else
          {
            [[ -f "$zshrc" ]] && cat "$zshrc"
            printf '\n'
            printf '# pgo launcher\n'
            printf '%s\n' "$path_line"
          } > "$tmp_zshrc"
        fi
        mv "$tmp_zshrc" "$zshrc"
        path_status="added launcher directory to $zshrc; open a new shell or run: source $zshrc"
      fi
    else
      path_status="launcher directory is not on PATH"
    fi
    ;;
esac

cat <<EOF
pgo launcher installed: $bin_dir/pgo
pgo project config: $config_path ($config_status)
PATH status: $path_status

Project paths, base URL, and model settings live in:
  $config_path

Setup scripts:
  $provider_script
      Configure the required OpenAI-compatible base URL and model ID,
      then store the provider API key in macOS Keychain.
      Re-running it replaces the existing default provider settings.
  $project_script
      Add or update a named workspace.
  $key_script
      Rotate the stored API key later.

Next steps:
  1. Make sure Docker Desktop is running.
  2. Build the Docker runtime:
       $build_path
  3. Add the required provider/model config and API key:
       $provider_script
  4. Add a named workspace:
       $project_script
EOF

case ":$PATH:" in
  *":$bin_dir:"*)
    cat <<EOF
  5. Start interactive mode:
       pgo PROJECT_NAME
EOF
    ;;
  *)
    cat <<EOF
  5. Open a new shell, or reload your current one.
     The installer updates ~/.zshrc, but it cannot reload the parent shell for you:
       source "\$HOME/.zshrc"
  6. Start interactive mode:
       pgo PROJECT_NAME
EOF
    ;;
esac
